#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#no gap when window is alone
#yabai -m signal --add event=application_launched action="~/.bin/padding.sh"
#yabai -m signal --add event=application_terminated action="~/.bin/padding.sh"
#
#yabai -m signal --add event=window_created action="~/.bin/padding.sh"
#yabai -m signal --add event=window_destroyed action="~/.bin/padding.sh"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xffa3be8c
yabai -m config normal_window_border_color   0x00555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  06
yabai -m config bottom_padding               06
yabai -m config left_padding                 06
yabai -m config right_padding                06
yabai -m config window_gap                   06

yabai -m rule --add app="^emacs$" title=".*" manage=on layer=normal
yabai -m rule --add app="zathura$" manage=on
yabai -m rule --add app="Brave$" manage=on
yabai -m rule --add app="Element$" manage=on
yabai -m rule --add app="Alacritty$" manage=on
yabai -m rule --add app="qutebrowser" title!="^$" role="AXWindow" subrole="AXDialog" manage=on

yabai -m rule --add app="System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="Docker Desktop$" layer=above manage=off
yabai -m rule --add app="Wally$" layer=above manage=off
yabai -m rule --add app="Inkscape$" layer=above manage=off
yabai -m rule --add app="scrcpy$" layer=above manage=off
yabai -m rule --add app="Steam$" layer=above manage=off

echo "yabai configuration loaded.."
