
[window]
decorations = "buttonless"
opacity = 0.94
[window.padding]
x = 5
y = 5

[font]
size = 16.0
[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"
[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"
[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light"
[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[general]
import = ["~/.config/alacritty/everforest_dark.toml"]
